[workspace]
resolver = "2"
members = [
    "forc",
    "forc-pkg",
    "forc-plugins/forc-client",
    "forc-plugins/forc-doc",
    "forc-plugins/forc-fmt",
    "forc-plugins/forc-lsp",
    "forc-plugins/forc-tx",
    "forc-test",
    "forc-tracing",
    "forc-util",
    "scripts/mdbook-forc-documenter",
    "sway-ast",
    "sway-core",
    "sway-error",
    "sway-ir",
    "sway-ir/sway-ir-macros",
    "sway-lsp",
    "sway-parse",
    "sway-types",
    "sway-utils",
    "swayfmt",
    "test",
]
exclude = [
    "examples/*",
    "swayfmt/test_macros",
    "forc-test/test_data"
]

[workspace.dependencies]
fuel-asm = "0.34.1"
fuel-crypto = "0.34.1"
fuel-types = "0.34.1"
fuel-tx = "0.34.1"
fuel-core-client = { version = "0.19.1", default-features = false }
fuel-vm = "0.34.1"
# fuels-core = "0.43"
# fuels-accounts = "0.43"
fuels-core = { git = "https://github.com/FuelLabs/fuels-rs", branch = "iqdecay/deps-fuel-core-update" }
fuels-accounts = { git = "https://github.com/FuelLabs/fuels-rs", branch = "iqdecay/deps-fuel-core-update" }

[workspace.package]
edition = "2021"
authors = ["Fuel Labs <contact@fuel.sh>"]
homepage = "https://fuel.network/"
license = "Apache-2.0"
repository = "https://github.com/FuelLabs/sway"
